
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA DIVIDE ELSE FUNC IF LPAREN MINUS MULTIPLY NUMBER PLUS RPAREN SEMICOLON VARIABLE WHILEstatement : expression SEMICOLONexpression : expression PLUS expression\n    | expression MINUS expression\n    | expression MULTIPLY expression\n    | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : VARIABLE'
    
_lr_action_items = {'LPAREN':([0,3,7,8,9,10,],[3,3,3,3,3,3,]),'NUMBER':([0,3,7,8,9,10,],[4,4,4,4,4,4,]),'VARIABLE':([0,3,7,8,9,10,],[5,5,5,5,5,5,]),'$end':([1,6,],[0,-1,]),'SEMICOLON':([2,4,5,12,13,14,15,16,],[6,-7,-8,-2,-3,-4,-5,-6,]),'PLUS':([2,4,5,11,12,13,14,15,16,],[7,-7,-8,7,7,7,7,7,-6,]),'MINUS':([2,4,5,11,12,13,14,15,16,],[8,-7,-8,8,8,8,8,8,-6,]),'MULTIPLY':([2,4,5,11,12,13,14,15,16,],[9,-7,-8,9,9,9,9,9,-6,]),'DIVIDE':([2,4,5,11,12,13,14,15,16,],[10,-7,-8,10,10,10,10,10,-6,]),'RPAREN':([4,5,11,12,13,14,15,16,],[-7,-8,16,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,7,8,9,10,],[2,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression SEMICOLON','statement',2,'p_statement_expr','gui.py',7),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','gui.py',12),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','gui.py',13),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression_binop','gui.py',14),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','gui.py',15),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','gui.py',20),
  ('expression -> NUMBER','expression',1,'p_expression_number','gui.py',25),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','gui.py',30),
]
